name: CodeTour watch

on:
    # all triggers are temporarily switched off
    # see https://github.com/yt-project/yt/issues/4213
    #pull_request:
    #    types: [opened, edited, synchronize, reopened]

jobs:
    codetour-watch:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v3

            - name: 'Watch CodeTour changes'
              uses: pozil/codetour-watch@v1.5.0
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
